# Generated by Django 4.0.4 on 2022-05-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('factor', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
